/*
 * Copyright (C) 2011 Flamingo Project (http://www.cloudine.io).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * ViewModel for Flamingo2.view.main.About
 *
 * @author Haneul, Kim
 * @since 2.1.0
 * @see Flamingo2.view.main.About
 */
Ext.define('Flamingo2.view.main.AboutModel', {
    extend: 'Ext.app.ViewModel',

    alias: 'viewmodel.about',

    stores: {
        dependency: {
            fields: ['project', 'license', 'organization', 'homepage',
                {
                    name: 'organ', mapping: 'organization',
                    convert: function (organization, record) {
                        var organ = '';
                        if (!isBlank(organization)) {
                            organ = '<a href="' + record.get('homepage') + '" target="_blank">' + organization + '</a>';
                        }
                        return organ;
                    }
                }
            ],
            data: [
                {project: 'HikariCP Java6', license: 'The Apache Software License, Version 2.0', organization: 'Zaxxer.com', homepage: 'https://github.com/brettwooldridge/HikariCP'},
                {project: 'StringTemplate 4', license: 'BSD licence', organization: '', homepage: ''},
                {project: 'JavaBeans(TM) Activation Framework', license: ' Common Development and Distribution License (CDDL) v1.0', organization: '', homepage: ''},
                {project: 'Activiti BPMN Converter', license: '', organization: '', homepage: ''},
                {project: 'Activiti BPMN Layout', license: '', organization: '', homepage: ''},
                {project: 'Activiti BPMN Model', license: '', organization: '', homepage: ''},
                {project: 'Activiti Engine', license: '', organization: '', homepage: ''},
                {project: 'Activiti Image Generator', license: '', organization: '', homepage: ''},
                {project: 'Activiti Process Validation', license: '', organization: '', homepage: ''},
                {project: 'Activiti Spring', license: '', organization: '', homepage: ''},
                {project: 'Apache Ant Core', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Ant Launcher', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Ankus', license: 'GPL v3 License', organization: 'ONYCOM', homepage: 'http://www.onycom.com'},
                {project: 'Antlr', license: 'BSD License', organization: '', homepage: ''},
                {project: 'ANTLR 3 Runtime', license: '', organization: '', homepage: ''},
                {project: 'ANTLR 4 Tool', license: '', organization: '', homepage: ''},
                {project: 'ANTLR 4 Runtime', license: '', organization: '', homepage: ''},
                {project: 'AOP Alliance', license: 'Public Domain', organization: '', homepage: ''},
                {project: 'ApacheDS I18n', license: '', organization: '', homepage: ''},
                {project: 'ApacheDS Protocol Kerberos Codec', license: '', organization: '', homepage: ''},
                {project: 'Apache Directory API ASN.1 API', license: '', organization: '', homepage: ''},
                {project: 'Apache Directory LDAP API Utilities', license: '', organization: '', homepage: ''},
                {project: 'ASM Helper Minidev', license: '', organization: '', homepage: ''},
                {project: 'ASM Core', license: '', organization: '', homepage: ''},
                {project: 'AspectJ Runtime', license: 'Eclipse Public License - v 1.0', organization: '', homepage: ''},
                {project: 'AspectJ Tools', license: 'Eclipse Public License - v 1.0', organization: '', homepage: ''},
                {project: 'AspectJ Weaver', license: 'Eclipse Public License - v 1.0', organization: '', homepage: ''},
                {project: 'Apache Avro', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Avro IPC', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Avro IPC', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Avro Mapred API', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'AWS SDK For Java', license: 'Apache License, Version 2.0', organization: '', homepage: ''},
                {project: 'Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, And CRMF APIs', license: 'Bouncy Castle Licence	', organization: '', homepage: ''},
                {project: 'Bouncy Castle Provider', license: 'Bouncy Castle Licence	', organization: '', homepage: ''},
                {project: 'BoneCP :: Core Library', license: '', organization: '', homepage: ''},
                {project: 'uEngine BPMN', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'Bean Scripting Framework', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Bring Your Own Node Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Chef Api', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Cloudservers Api', license: '', organization: '', homepage: ''},
                {project: 'Jclouds CloudServers UK Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds CloudServers US Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Cloudstack Core', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons BeanUtils', license: '', organization: '', homepage: ''},
                {project: 'Commons BeanUtils Core', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons CLI', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Codec', license: '', organization: '', homepage: ''},
                {project: 'Commons Collections', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Compress', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Configuration', license: 'The Apache Software License, Version 2.0', organization: 'The Apache Software Foundation', homepage: 'http://commons.apache.org/'},
                {project: 'Commons Daemon', license: '', organization: '', homepage: ''},
                {project: 'Commons DBCP', license: '', organization: '', homepage: ''},
                {project: 'Commons Digester', license: 'The Apache Software License, Version 2.0', organization: 'The Apache Software Foundation', homepage: 'http://jakarta.apache.org/'},
                {project: 'EL', license: 'The Apache Software License, Version 2.0', organization: 'The Apache Software Foundation', homepage: 'http://jakarta.apache.org/'},
                {project: 'Apache Commons Email', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Exec', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons FileUpload', license: '', organization: '', homepage: ''},
                {project: 'HttpClient', license: 'Apache License', organization: 'Apache Software Foundation', homepage: 'http://jakarta.apache.org/'},
                {project: 'Commons IO', license: '', organization: '', homepage: ''},
                {project: 'Commons Lang', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Lang', license: '', organization: '', homepage: ''},
                {project: 'Apache Commons Logging', license: '', organization: '', homepage: ''},
                {project: 'Logging', license: 'The Apache Software License, Version 2.0', organization: 'The Apache Software Foundation', homepage: 'http://jakarta.apache.org/'},
                {project: 'Apache Commons Math', license: '', organization: '', homepage: ''},
                {project: 'Commons Net', license: '', organization: '', homepage: ''},
                {project: 'Commons Pool', license: '', organization: '', homepage: ''},
                {project: 'Java Development Tools Core', license: 'Eclipse Public License v1.0', organization: '', homepage: ''},
                {project: 'Curator Client', license: '', organization: '', homepage: ''},
                {project: 'Curator Framework', license: '', organization: '', homepage: ''},
                {project: 'Curator Recipes', license: '', organization: '', homepage: ''},
                {project: 'DataNucleus JDO API Plugin', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'DataNucleus Core', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'DataNucleus RDBMS Plugin', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Derby Database Engine And Embedded JDBC Driver', license: '', organization: '', homepage: ''},
                {project: 'Disruptor Framework', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'DSpace Maxmind GeoIP Dependency', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Ec2 Api', license: '', organization: '', homepage: ''},
                {project: 'Ehcache Core', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Jclouds ElasticHosts BlueSquare London Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds ElasticHosts Peer1 London Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds ElasticHosts Peer1 San Antonio Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Elasticstack Core', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Enterprise Chef Provider', license: '', organization: '', homepage: ''},
                {project: 'Expectit :: Core', license: '', organization: '', homepage: ''},
                {project: 'Flamingo 2 - Common', license: 'GNU GENERAL PUBLIC LICENSE Version 3', organization: 'Cloudine, Inc.', homepage: 'http://www.cloudine.io/'},
                {project: 'Flamingo 2 - License', license: 'GNU GENERAL PUBLIC LICENSE Version 3', organization: 'Cloudine, Inc.', homepage: 'http://www.cloudine.io/'},
                {project: 'Gmetric4j', license: 'The MIT License', organization: '', homepage: ''},
                {project: 'Jclouds Go2Cloud Johannesburg1 Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds GoGrid Provider', license: '', organization: '', homepage: ''},
                {project: 'Apache Groovy', license: 'The Apache Software License, Version 2.0', organization: 'The Codehaus', homepage: 'http://codehaus.org/'},
                {project: 'Goldman Sachs Collections Main Library', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Goldman Sachs Collections API', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Gson', license: 'The Apache Software License, Version 2.0', organization: 'Google, Inc.', homepage: 'http://www.google.com/'},
                {project: 'Guava: Google Core Libraries For Java', license: '', organization: '', homepage: ''},
                {project: 'Google Guice Core Library', license: '', organization: '', homepage: ''},
                {project: 'Google Guice Extensions AssistedInject', license: '', organization: '', homepage: ''},
                {project: 'Google Guice Extensions MultiBindings', license: '', organization: '', homepage: ''},
                {project: 'Google Guice Extensions Servlet', license: '', organization: '', homepage: ''},
                {project: 'Apache Hadoop Annotations', license: '', organization: '', homepage: ''},
                {project: 'Apache Hadoop Auth', license: '', organization: '', homepage: ''},
                {project: 'Apache Hadoop Common', license: '', organization: '', homepage: ''},
                {project: 'Apache Hadoop HDFS', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Mapreduce Client Common', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Mapreduce Client Core', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Mapreduce Client Jobclient', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Mapreduce Client Shuffle', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Yarn Api', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Yarn Client', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Yarn Common', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Yarn Server Common', license: '', organization: '', homepage: ''},
                {project: 'Hadoop Yarn Server Nodemanager', license: '', organization: '', homepage: ''},
                {project: 'Hive Ant Utilities', license: '', organization: '', homepage: ''},
                {project: 'Hive Common', license: '', organization: '', homepage: ''},
                {project: 'Hive Query Language', license: '', organization: '', homepage: ''},
                {project: 'Hive JDBC', license: '', organization: '', homepage: ''},
                {project: 'Hive Metastore', license: '', organization: '', homepage: ''},
                {project: 'Hive Serde', license: '', organization: '', homepage: ''},
                {project: 'Hive Service', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims 0.20', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims 0.20S', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims 0.23', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims Common', license: '', organization: '', homepage: ''},
                {project: 'Hive Shims Secure Common', license: '', organization: '', homepage: ''},
                {project: 'Jclouds HP Cloud Compute Provider', license: '', organization: '', homepage: ''},
                {project: 'Htrace Core', license: '', organization: '', homepage: ''},
                {project: 'Apache HttpClient', license: '', organization: '', homepage: ''},
                {project: 'Apache HttpCore', license: '', organization: '', homepage: ''},
                {project: 'Apache HttpClient Mime', license: '', organization: '', homepage: ''},
                {project: 'Jackson Annotations', license: '', organization: '', homepage: ''},
                {project: 'Jackson Core', license: '', organization: '', homepage: ''},
                {project: 'Jackson', license: 'The Apache Software License, Version 2.0', organization: 'FasterXML', homepage: 'http://fasterxml.com/'},
                {project: 'Jackson Databind', license: '', organization: '', homepage: ''},
                {project: 'JAX RS Provider For JSON Content Type', license: 'The Apache Software License, Version 2.0, GNU Lesser General Public License (LGPL), Version 2.1', organization: 'FasterXML', homepage: 'http://fasterxml.com/'},
                {project: 'Data Mapper For Jackson', license: 'The Apache Software License, Version 2.0', organization: 'FasterXML', homepage: 'http://fasterxml.com/'},
                {project: 'Xml Compatibility Extensions For Jackson', license: 'The Apache Software License, Version 2.0, GNU Lesser General Public License (LGPL), Version 2.1', organization: 'FasterXML', homepage: 'http://fasterxml.com/'},
                {project: 'Janino', license: 'BSD', organization: '', homepage: ''},
                {project: 'Jansi', license: '', organization: '', homepage: ''},
                {project: 'Java Xmlbuilder', license: 'Apache License, Version 2.0', organization: '', homepage: ''},
                {project: 'Javassist', license: 'MPL 1.1, LGPL 2.1, Apache License 2.0', organization: '', homepage: ''},
                {project: 'Javax.annotation API V.1.0', license: '', organization: '', homepage: ''},
                {project: 'Javax.ejb API V.3.1', license: '', organization: '', homepage: ''},
                {project: 'Javax.inject', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Java Servlet API', license: 'CDDL + GPLv2 with classpath exception', organization: 'GlassFish Community', homepage: 'https://glassfish.dev.java.net/'},
                {project: 'Javax.transaction API V.1.1', license: '', organization: '', homepage: ''},
                {project: 'Java Architecture For XML Binding', license: '', organization: '', homepage: ''},
                {project: 'Old JAXB Runtime', license: 'CDDL 1.0, GPL2 w/ CPE', organization: '', homepage: ''},
                {project: 'Old JAXB XJC', license: 'CDDL 1.0, GPL2 w/ CPE', organization: '', homepage: ''},
                {project: 'jazzlib-1.0.0.jar', license: '', organization: '', homepage: ''},
                {project: 'Jboss J2ee', license: '', organization: '', homepage: ''},
                {project: 'JCL 1.1.1 Implemented Over SLF4J', license: '', organization: '', homepage: ''},
                {project: 'Allcompute', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Bouncycastle EncryptionService Module', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Compute Core', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Components Core', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Script Builder', license: '', organization: '', homepage: ''},
                {project: 'Jclouds SLF4J Logging Module', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Sshj Ssh Client', license: '', organization: '', homepage: ''},
                {project: 'JDO API', license: 'Apache 2', organization: 'Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'Jersey Client', license: '', organization: '', homepage: ''},
                {project: 'Jersey Core', license: '', organization: '', homepage: ''},
                {project: 'Jersey Guice', license: '', organization: '', homepage: ''},
                {project: 'Jersey Json', license: '', organization: '', homepage: ''},
                {project: 'Jersey Server', license: '', organization: '', homepage: ''},
                {project: 'JetS3t', license: 'Apache License, Version 2.0', organization: '', homepage: ''},
                {project: 'Jettison', license: '', organization: '', homepage: ''},
                {project: 'Jetty :: Server Core', license: '', organization: '', homepage: ''},
                {project: 'Jetty :: Utilities', license: '', organization: '', homepage: ''},
                {project: 'JGraphT', license: 'GNU Lesser General Public License Version 2.1, February 1999', organization: '', homepage: ''},
                {project: 'JGraph X', license: 'JGraph Ltd - 3 clause BSD license', organization: 'JGraph Ltd', homepage: 'http://www.jgraph.com/'},
                {project: 'JLine', license: 'BSD', organization: '', homepage: ''},
                {project: 'Java Native Access', license: 'LGPL, version 2.1, ASL, version 2', organization: '', homepage: ''},
                {project: 'Java Native Access Platform', license: 'LGPL, version 2.1, ASL, version 2', organization: '', homepage: ''},
                {project: 'Joda Time', license: 'Apache 2', organization: 'joda.org', homepage: 'http://www.joda.org/'},
                {project: 'Jodd Core', license: 'The New BSD License', organization: 'Jodd', homepage: 'http://jodd.org/'},
                {project: 'JPam', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'JSch', license: 'Revised BSD', organization: 'JCraft,Inc.', homepage: 'http://www.jcraft.com/'},
                {project: 'A Connector Factory', license: '', organization: '', homepage: ''},
                {project: 'Jsch Agent Proxy Core Library', license: '', organization: '', homepage: ''},
                {project: 'A Connector For Pageant Using JNA', license: '', organization: '', homepage: ''},
                {project: 'A Connector For Ssh Agent', license: '', organization: '', homepage: ''},
                {project: 'A Library To Use Jsch Agent Proxy With Sshj', license: '', organization: '', homepage: ''},
                {project: 'An Implementation Of USocketFactory Using JNA', license: '', organization: '', homepage: ''},
                {project: 'An Implementation Of USocketFactory Using Netcat', license: '', organization: '', homepage: ''},
                {project: 'Json Path', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'JSON Small And Fast Parser', license: '', organization: '', homepage: ''},
                {project: 'Jsr166e', license: 'Public Domain', organization: '', homepage: ''},
                {project: 'JSR 250 Common Annotations For The JavaTM Platform', license: 'COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0', organization: '', homepage: ''},
                {project: 'FindBugs Jsr305', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Jsr311 Api', license: 'CDDL License', organization: '', homepage: ''},
                {project: 'Jstl', license: '', organization: '', homepage: ''},
                {project: 'Java Transaction API', license: '', organization: '', homepage: ''},
                {project: 'JUL To SLF4J Bridge', license: '', organization: '', homepage: ''},
                {project: 'Leveldbjni All', license: '', organization: '', homepage: ''},
                {project: 'Apache Thrift', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Thrift', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'LicenseManager Core', license: '', organization: '', homepage: ''},
                {project: 'Apache Log4j', license: 'The Apache Software License, Version 2.0', organization: 'Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'Log4j Implemented Over SLF4J', license: 'Apache Software Licenses', organization: '', homepage: ''},
                {project: 'Log4jdbc Remix', license: 'Apache 2', organization: '', homepage: ''},
                {project: 'Logback Classic Module', license: 'Eclipse Public License - v 1.0, GNU Lesser General Public License', organization: '', homepage: ''},
                {project: 'Logback Core Module', license: 'Eclipse Public License - v 1.0, GNU Lesser General Public License', organization: '', homepage: ''},
                {project: 'JavaMail API (compat)', license: '', organization: '', homepage: ''},
                {project: 'uEngine Metaworks', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'uEngine Metaworks2', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'uEngine Metaworks3', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'Metrics Core', license: '', organization: '', homepage: ''},
                {project: 'JVM Integration For Metrics', license: '', organization: '', homepage: ''},
                {project: 'Mybatis', license: '', organization: '', homepage: ''},
                {project: 'Mybatis Spring', license: '', organization: '', homepage: ''},
                {project: 'MySQL Connector/J', license: 'The GNU General Public License, Version 2', organization: '', homepage: ''},
                {project: 'Netty/All In One', license: 'Apache License, Version 2.0', organization: 'The Netty Project', homepage: 'http://netty.io/'},
                {project: 'Netty/Buffer', license: '', organization: '', homepage: ''},
                {project: 'Netty/Codec', license: '', organization: '', homepage: ''},
                {project: 'Netty/Codec/HTTP', license: '', organization: '', homepage: ''},
                {project: 'Netty/Common', license: '', organization: '', homepage: ''},
                {project: 'Netty/Handler', license: '', organization: '', homepage: ''},
                {project: 'Netty/Transport', license: '', organization: '', homepage: ''},
                {project: 'Remote Tea Runtime', license: 'GNU Lesser General Public License', organization: '', homepage: ''},
                {project: 'Jclouds Open Hosting East1 Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds OpenStack Components Core', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Openstack Keystone Api', license: '', organization: '', homepage: ''},
                {project: 'Apache Jclouds :: OpenStack :: Nova API', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Openstack Nova Ec2 Api', license: '', organization: '', homepage: ''},
                {project: 'Abego TreeLayout Core Demo', license: 'BSD 3-Clause "New" or "Revised" License (BSD-3-Clause)', organization: 'abego Software GmbH, Germany', homepage: 'http://abego-software.de/'},
                {project: 'Oro', license: '', organization: '', homepage: ''},
                {project: 'ParaNamer Core', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Column (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Common (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Encodings (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Format (Incubating)', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'Apache Parquet Generator (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Hadoop (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Apache Parquet Jackson (Incubating)', license: '', organization: '', homepage: ''},
                {project: 'Persistence Api', license: 'Common Development and Distribution License (CDDL) v1.0', organization: '', homepage: ''},
                {project: 'Apache POI', license: 'The Apache Software License, Version 2.0', organization: 'Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'Apache POI ooxml', license: 'The Apache Software License, Version 2.0', organization: 'Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'Apache POI ooxml schemas', license: 'The Apache Software License, Version 2.0', organization: 'Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'PostgreSQL JDBC Driver', license: 'The PostgreSQL License', organization: '', homepage: ''},
                {project: 'Protocol Buffer Java API', license: 'New BSD license', organization: '', homepage: ''},
                {project: 'Quartz', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Rackspace Cloudidentity Api', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Rackspace Next Generation Cloud Servers Provider', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Rackspace Next Generation Cloud Servers US Provider', license: '', organization: '', homepage: ''},
                {project: 'Core Reactor Components', license: 'The Apache Software License, Version 2.0', organization: 'reactor', homepage: 'http://github.com/reactor'},
                {project: 'Reactor Spring Context Components', license: 'The Apache Software License, Version 2.0', organization: 'reactor', homepage: 'http://github.com/reactor'},
                {project: 'Reactor Spring Core Components', license: 'The Apache Software License, Version 2.0', organization: 'reactor', homepage: 'http://github.com/reactor'},
                {project: 'Mozilla Rhino', license: 'Mozilla Public License, Version 2.0', organization: 'The Mozilla Foundation', homepage: 'http://www.mozilla.org/'},
                {project: '99soft :: Rocoto', license: '', organization: '', homepage: ''},
                {project: 'Jclouds Serverlove Manchester Provider', license: '', organization: '', homepage: ''},
                {project: 'Sigar', license: '', organization: '', homepage: ''},
                {project: 'Jclouds SkaliCloud Malaysia Provider', license: '', organization: '', homepage: ''},
                {project: 'SLF4J API Module', license: '', organization: '', homepage: ''},
                {project: 'SnakeYAML', license: 'Apache License Version 2.0', organization: '', homepage: ''},
                {project: 'Snappy Java', license: 'The Apache Software License, Version 2.0', organization: 'xerial.org', homepage: 'http://www.xerial.org/'},
                {project: 'Jclouds SoftLayer Core', license: '', organization: '', homepage: ''},
                {project: 'Spring AOP', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Aspects', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Beans', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Context', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Context Support', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Core', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Expression Language (SpEL)', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring JDBC', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Messaging', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Object/Relational Mapping', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Object/XML Marshalling', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Acl', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Aspects', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Config', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Core', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Taglibs', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Security Web', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Transaction', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Web', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring Web MVC', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Spring WebSocket', license: 'The Apache Software License, Version 2.0', organization: 'Spring IO', homepage: 'http://projects.spring.io/spring-framework'},
                {project: 'Sshj', license: 'Apache 2', organization: '', homepage: ''},
                {project: 'Standard', license: '', organization: '', homepage: ''},
                {project: 'Streaming API For XML', license: 'GNU General Public Library, COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0', organization: '', homepage: ''},
                {project: 'StAX API', license: 'The Apache Software License, Version 2.0', organization: '', homepage: ''},
                {project: 'ANTLR StringTemplate 4.0.2', license: 'BSD license', organization: '', homepage: ''},
                {project: 'Jclouds Sts Api', license: '', organization: '', homepage: ''},
                {project: 'Tajo Algebra', license: '', organization: '', homepage: ''},
                {project: 'Tajo Catalog Client', license: '', organization: '', homepage: ''},
                {project: 'Tajo Catalog Common', license: '', organization: '', homepage: ''},
                {project: 'Tajo Catalog Server', license: '', organization: '', homepage: ''},
                {project: 'Tajo CLI Tools', license: '', organization: '', homepage: ''},
                {project: 'Tajo Client', license: '', organization: '', homepage: ''},
                {project: 'Tajo Common', license: '', organization: '', homepage: ''},
                {project: 'Tajo Core', license: '', organization: '', homepage: ''},
                {project: 'Tajo JDBC Driver', license: '', organization: '', homepage: ''},
                {project: 'Tajo Plan', license: '', organization: '', homepage: ''},
                {project: 'Tajo PullServer', license: '', organization: '', homepage: ''},
                {project: 'Tajo Rpc', license: '', organization: '', homepage: ''},
                {project: 'Tajo Storage Common', license: '', organization: '', homepage: ''},
                {project: 'Tajo HDFS Storage', license: '', organization: '', homepage: ''},
                {project: 'ASM (thirdparty)', license: '', organization: '', homepage: ''},
                {project: 'Trevni Java Avro', license: '', organization: '', homepage: ''},
                {project: 'Trevni Java Core', license: '', organization: '', homepage: ''},
                {project: 'uEngine BPMN Modeler', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'uEngine Core', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'uEngine Modeling', license: 'LGPL', organization: 'uEngine', homepage: 'http://www.uengine.org/web/guest/home'},
                {project: 'Bean Validation API', license: 'Apache License, Version 2.0', organization: '', homepage: ''},
                {project: 'Jclouds Vcloud Api', license: '', organization: '', homepage: ''},
                {project: 'Apache Velocity', license: 'The Apache Software License, Version 2.0', organization: 'The Apache Software Foundation', homepage: 'http://www.apache.org/'},
                {project: 'Xerces2 J', license: '', organization: '', homepage: ''},
                {project: 'Xml Apis', license: '', organization: '', homepage: ''},
                {project: 'XmlBeans', license: 'The Apache Software License, Version 2.0', organization: 'XmlBeans', homepage: 'http://xmlbeans.apache.org/'},
                {project: 'Xmlenc Library', license: 'The BSD License', organization: '', homepage: ''},
                {project: 'XMLUnit For Java', license: 'BSD License', organization: '', homepage: ''},
                {project: 'MXP1: Xml Pull Parser 3rd Edition (XPP3)', license: 'Indiana University Extreme! Lab Software License, vesion 1.1.1, Public Domain', organization: 'Extreme! Lab, Indiana University', homepage: 'http://www.extreme.indiana.edu/'},
                {project: 'XStream Core', license: '', organization: '', homepage: ''},
                {project: 'XZ For Java', license: 'Public Domain', organization: '', homepage: ''},
                {project: 'Zookeeper', license: '', organization: '', homepage: ''}
            ]
        }
    }
});